### Variables
@apiurl = http://localhost:3000/

GET http://localhost:3000/

###
 
POST {{apiurl}}
Content-Type: application/json

{
    "email": "test@email.com",
    "question": "how much is 14 squared?"
}

